version: "3.7"

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - "/code:/code:rw"
            - "/code/local/docker/conf/nginx:/etc/nginx:ro"
        depends_on:
            - php-fpm-5.6.38
            - php-fpm-7.2.12
        links:
            - php-fpm-5.6.38
            - php-fpm-7.2.12

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - "/code/redis-data:/data:rw"
            # Docker Redis server have no configure file.

    php-fpm-5.6.38:
        image: t895469945/php:5.6.38-fpm
        ports:
            - "15638:9000"
        volumes:
            - "/code:/code:rw"
            - "/code/local/docker/conf/php-5.6:/usr/local/php/etc:ro"
        depends_on:
            - redis
        links:
            - redis

    php-fpm-7.2.12:
        image: t895469945/php:7.2.12-fpm
        ports:
            - "17212:9000"
        volumes:
            - "/code:/code:rw"
            - "/code/local/docker/conf/php-7.2:/usr/local/php/etc:ro"
        depends_on:
            - redis
        links:
            - redis




