version: "3.7"

networks: 
  elastic:
    driver: bridge
    ipam: 
      driver: default
      config: 
        -
          subnet: 172.16.254.0/24

services: 
  node-01:
    env_file: .env
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    networks: 
      elastic:
        aliases:
          - "node-01"
        ipv4_address: 172.16.254.11
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "1"
    environment: 
      node.name: "node-01"
    volumes: 
      - "./data-01:/usr/share/elasticsearch/data"
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./analysis-ik/custom-word-list:/usr/share/elasticsearch/config/analysis-ik/custom"
    ports:
      - "19200:9200"
  node-02:
    env_file: .env
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    networks: 
      elastic:
        aliases:
          - "node-02"
        ipv4_address: 172.16.254.21
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "1"
    environment: 
      node.name: "node-02"
    volumes: 
      - "./data-02:/usr/share/elasticsearch/data"
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./analysis-ik/custom-word-list:/usr/share/elasticsearch/config/analysis-ik/custom"
    ports:
      - "29200:9200"
  node-03:
    env_file: .env
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    networks: 
      elastic:
        aliases:
          - "node-03"
        ipv4_address: 172.16.254.31
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "1"
    environment: 
      node.name: "node-02"
    volumes: 
      - "./data-03:/usr/share/elasticsearch/data"
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./analysis-ik/custom-word-list:/usr/share/elasticsearch/config/analysis-ik/custom"
    ports:
      - "39200:9200"
  es-wm:
    env_file: .env
    image: docker.elastic.co/kibana/kibana:7.6.1
    networks:
      elastic:
        aliases:
          - "es-wm"
        ipv4_address: 172.16.254.101
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "1"
    depends_on: 
      - node-01
      - node-02
    volumes: 
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - "5601:5601"
